name: Build 0
on:
  push:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/archlinux365/9318-archlinux-docker/root:latest
      volumes:
        - /home/runner/work/alterdir/alterdir:/tmp/alterdir
      options: "--privileged"
    steps:
      - uses: actions/checkout@v2
      - name: 1. Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.MY_SF_SSH }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
      - name: 2. build
        run: |
          # 展开
          echo "::group::Set github-actions bot"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          echo "::group::Set Key & Hosts"
          cp -fv known_hosts /root/.ssh/known_hosts
          ssh-keygen -f "/root/.ssh/known_hosts" -R "github.com"
          ssh-keyscan "github.com" >> /root/.ssh/known_hosts
          cat /root/.ssh/known_hosts
          echo "::group::Build"
          ./build-for-github.sh
          echo "::group::Push To GitHub"
          git add .
          git commit -a -m "add"
          git push origin HEAD
