name: Build 0
on:
  push:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/archlinux365/9318-archlinux-docker/root:latest
      volumes:
        - /home/runner/work/alterdir/alterdir:/tmp/alterdir
      options: "--privileged"
    steps:
      - name: 1. Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.MY_SF_SSH }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - uses: actions/checkout@v2
      - name: 2.build
        run: ./build-for-github.sh
